docs(set): add documentation to the set group
skyleague/axioms pull request #33
Opened 2022-10-31 08:39 UTC by pevisscher

2022-10-31 08:39 UTC, pevisscher commented
Current dependencies on/for this PR:
* main
  * **PR #30** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/30" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #31** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/31" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #32** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/32" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #33** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/33" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/axioms/33?utm_source=stack-comment).

2022-11-04 14:07 UTC, MickVanDuijn approved these changes

2022-11-04 14:07 UTC, MickVanDuijn commented on src/set/is-disjoint/is-disjoint.ts
> + * A disjoint set is a set of elements that have no members in common.
```suggestion
 * Two sets of elements are disjoint when they have no members in common.
```

2022-11-04 14:07 UTC, MickVanDuijn commented on src/set/is-disjoint/is-disjoint.ts
> + * If either approach returns true, then the sets are not disjoint and hence they are not mutually exclusive.
```suggestion
 * This problem can be solved by checking if there is any member of the first set, that is also a member of the second set.
 * If there exists such a member, then the sets are not mutually exclusive.
```

2022-11-04 14:07 UTC, MickVanDuijn commented on src/set/is-subset/is-subset.ts
> + * A set is a subset of the superset if it contains all the elements in the superset.
```suggestion
 * A set is a subset of the superset if all elements are contained in the superset.
```

2022-11-04 14:07 UTC, MickVanDuijn commented on src/set/is-superset/is-super.ts
> + * We check whether each element in the superset belong to the subset.
```suggestion
 * We check whether each element in the subset belong to the superset.
```

2022-11-04 14:07 UTC, MickVanDuijn requested changes
See inline comments

2022-11-04 14:08 UTC, MickVanDuijn approved these changes

2022-11-04 17:36 UTC, pevisscher commented
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/axioms/33?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: K5yEkBD2dLgv1WFxOfGc

2022-11-04 17:42 UTC, merged