feat(try): add try construct
skyleague/axioms pull request #42
Opened 2022-11-18 15:33 UTC by pevisscher

2022-11-18 15:34 UTC, pevisscher commented
Current dependencies on/for this PR:
* main
  * **PR #38** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/38" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #41** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/41" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #42** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/42" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/axioms/42?utm_source=stack-comment).

2022-11-18 15:57 UTC, loredanamoanga approved these changes

2022-11-18 16:25 UTC, MickVanDuijn requested changes
See inline comments

2022-11-18 16:25 UTC, MickVanDuijn commented on src/guard/is-try/is-try.ts
> +    return x !== null && x !== undefined && typeof x === 'object' && ('success' in x || 'failure' in x)
```suggestion
    return true
```
everything is a try in the new definition I guess :laughing:

2022-11-23 08:54 UTC, MickVanDuijn approved these changes

2022-11-23 09:18 UTC, pevisscher commented
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/axioms/42?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: snArrRseLhXioPIul3WC

2022-11-23 09:21 UTC, merged